modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tester"
version="1.0.0"
displayName="TESTER"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FILIP, MCreator"

[[dependencies.tester]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




